formatter: markdown table

output:
  file: README.md
  mode: replace

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  description: true
  escape: true
  hide-empty: false
  indent: 2
  required: true
  sensitive: true
  type: true
